### ISSUE TITLE
Unable to install Oracle Docker Extension

### ISSUE THREAD

**Issue by Monte-Christo** [marcelo-ochoa/oraclexe-docker-extension#3]
I rebooted to make sure no ports were unnecessarily occupied. But I keep getting this error trying to install the extension on Win 10 Enterprise 22H2:

`
Failed to install extension: installation could not be completed due to: executing 'docker --context desktop-linux compose -p mochoa_oraclefree-docker-extension-desktop-extension -f C:\Users\edkn\AppData\Roaming\Docker\extensions\mochoa_oraclefree-docker-extension\vm\docker-compose.yml up -d' : exit status 1: Network mochoa_oraclefree-docker-extension-desktop-extension_default Creating Network mochoa_oraclefree-docker-extension-desktop-extension_default Created Volume "mochoa_oraclefree-docker-extension-desktop-extension_sqlcl_home" Creating Volume "mochoa_oraclefree-docker-extension-desktop-extension_sqlcl_home" Created Volume "mochoa_oraclefree-docker-extension-desktop-extension_oracle-volume" Creating Volume "mochoa_oraclefree-docker-extension-desktop-extension_oracle-volume" Created Container mochoa_oraclefree-docker-extension-desktop-extension-service Creating Container mochoa_oraclefree-docker-extension-desktop-extension-oraclefree-1 Creating Container mochoa_oraclefree-docker-extension-desktop-extension-service Created Container mochoa_oraclefree-docker-extension-desktop-extension-oraclefree-1 Created Container mochoa_oraclefree-docker-extension-desktop-extension-service Starting Container mochoa_oraclefree-docker-extension-desktop-extension-oraclefree-1 Starting Error response from daemon: driver failed programming external connectivity on endpoint mochoa_oraclefree-docker-extension-desktop-extension-service (7aac4861ec395139dd6797091c8079a7c0fc59114727a004854102f48f1d01dd): Bind for 0.0.0.0:59890 failed: port is already allocated
`

Digging a bit deeper I found 
```
> netstat -aof | findstr :'59890'
TCP    0.0.0.0:59890          AT02WP070.scdom.net:0  LISTENING       30724
```
and 
```
> tasklist | findstr '30724'
com.docker.backend.exe       30724 Console                    1     62┬á900 K
```

Not sure what to make of it or how to work around it.

**Comment by marcelo-ochoa** [comment]
Did you try first:
`docker pull gvenzl/oracle-free:23.2.0-faststart`
Oracle image is big and sometime the docker extension command do not wait until this image is ready.

**Comment by marcelo-ochoa** [comment]
Wait, I see that is port collition on Windows.
Let me see using other laptop which port is available for sqlcl endpoint.
Marcelo.

**Comment by marcelo-ochoa** [comment]
Try uninstalling/installing the extension.
I moved to 59830 port, it works on Windows 11.
Marcelo.

**Comment by Monte-Christo** [comment]
Works out of the box now. Thanks.
